# TODO: add variables (CC, CFLAGS, etc)

all: clean run

clean:
	rm -f upddb

debug:
	@echo "\tCC\t\tupddb.c"
	@gcc -ggdb -std=c99 -Wall -pedantic upddb.c -o upddb

release:
	@echo "\tCC\t\tupddb.c"
	@gcc -O3 -std=c99 -Wall -pedantic upddb.c -o upddb



run: release
	@echo "\tGEN\t\tchars.db"
	@./upddb > chars.db

install: run
	@echo "\tINSTALL\t\tchars.db"
	@install -m644 ./chars.db $HOME/.local/share/lcharmap/chars.db
